Include environment-dnf.sh in dng-host script.
Signed-off-by: Zheng Ruoqin <zhengrq.fnst@cn.fujitsu.com>

diff --git a/dnf-plugins/dnf-host b/dnf-plugins/dnf-host
--- a/dnf-plugins/dnf-host
+++ b/dnf-plugins/dnf-host
@@ -74,6 +74,143 @@ set_dir() {
         fi
 }
 
+export_env () {
+    echo "TARGET_ROOTFS=$DEFINE_ROOTFS_DIR" > $WORKDIR/.env-dnf
+    echo "HIDDEN_ROOTFS=$HIDDEN_ROOTFS_DIR" >> $WORKDIR/.env-dnf
+    echo "REPO_DIR=$DEFINE_REPO_DIR" >> $WORKDIR/.env-dnf
+    echo "SPDX_REPO_DIR=$DEFINE_SPDX_REPO_DIR" >> $WORKDIR/.env-dnf
+    echo "SPDX_DESTINATION_DIR=$DEFINE_SPDX_DESTINATION_DIR" >> $WORKDIR/.env-dnf
+    echo "SRPM_REPO_DIR=$DEFINE_SRPM_REPO_DIR" >> $WORKDIR/.env-dnf
+    echo "SRPM_DESTINATION_DIR=$DEFINE_SRPM_DESTINATION_DIR" >> $WORKDIR/.env-dnf
+    echo "RPM_REPO_DIR=$DEFINE_RPM_REPO_DIR" >> $WORKDIR/.env-dnf
+    echo "RPM_DESTINATION_DIR=$DEFINE_RPM_DESTINATION_DIR" >> $WORKDIR/.env-dnf
+    echo "LD_LIBRARY_PATH=$OECORE_NATIVE_SYSROOT/usr/bin/../lib/pseudo/lib:$OECORE_NATIVE_SYSROOT/usr/bin/../lib/pseudo/lib64" >> $WORKDIR/.env-dnf
+    echo "LD_PRELOAD=libpseudo.so" >> $WORKDIR/.env-dnf
+    echo "PSEUDO_PASSWD=$HIDDEN_ROOTFS_DIR" >> $WORKDIR/.env-dnf 
+    echo "PSEUDO_OPTS=" >> $WORKDIR/.env-dnf
+    echo "PSEUDO_LIBDIR=$OECORE_NATIVE_SYSROOT/usr/bin/../lib/pseudo/lib64" >> $WORKDIR/.env-dnf
+    echo "PSEUDO_NOSYMLINKEXP=1" >> $WORKDIR/.env-dnf
+    echo "PSEUDO_DISABLED=0" >> $WORKDIR/.env-dnf
+    echo "PSEUDO_PREFIX=$OECORE_NATIVE_SYSROOT/usr" >> $WORKDIR/.env-dnf
+    echo "PSEUDO_LOCALSTATEDIR=$WORKDIR/pseudo/" >> $WORKDIR/.env-dnf
+    echo "D=$HIDDEN_ROOTFS_DIR" >> $WORKDIR/.env-dnf
+    echo "OFFLINE_ROOT=$HIDDEN_ROOTFS_DIR" >> $WORKDIR/.env-dnf
+    echo "IPKG_OFFLINE_ROOT=$HIDDEN_ROOTFS_DIR" >> $WORKDIR/.env-dnf
+    echo "OPKG_OFFLINE_ROOT=$HIDDEN_ROOTFS_DIR" >> $WORKDIR/.env-dnf
+    echo "INTERCEPT_DIR=$WORKDIR/intercept_scripts" >> $WORKDIR/.env-dnf
+    echo "NATIVE_ROOT=$OECORE_NATIVE_SYSROOT" >> $WORKDIR/.env-dnf
+    echo "RPM_ETCCONFIGDIR=$HIDDEN_ROOTFS_DIR" >> $WORKDIR/.env-dnf
+}
+
+check_para () {
+#Check the parameters
+if [ ! -d $HIDDEN_ROOTFS_DIR ]; then
+    echo " $HIDDEN_ROOTFS_DIR is not exist. mkdir $HIDDEN_ROOTFS_DIR. "
+    mkdir -p $HIDDEN_ROOTFS_DIR
+fi
+}
+
+#create repodata for rpm packages.
+create_repo () {
+    if [ ${DEFINE_REPO_DIR:0:4} = "http" ];then
+        echo "This is a remote repo!"
+    else
+        if [ ! -d $DEFINE_REPO_DIR ]; then
+            echo "Error! $DEFINE_REPO_DIR is not exist. Please Check your rpm repo! "
+            exit 0
+        fi
+        echo "Creating repo ..."
+        if [ -f $DEFINE_REPO_DIR/comps.xml ]; then
+            createrepo_c.real --update -q -g comps.xml $DEFINE_REPO_DIR
+        else
+            createrepo_c.real --update -q $DEFINE_REPO_DIR
+        fi
+    fi
+}
+
+travFolder () { 
+    cd $1
+    #echo $flist
+    for f in `ls`
+    do
+        if [ "$f" = "repodata" ];then
+           continue 
+        fi
+        if test -d $f;then
+            travFolder $f
+        else
+            if [ "${f##*.}"x = "rpm"x ];then
+                line=`echo "$f" | sed -r 's/.*\.(.*)\.rpm/\1/'`
+                if [ "$line" != "all" ] && [ "$line" != "any" ] && [ "$line" != "noarch" ] && [ "$line" != "${ARCH}" ] && [ "$line" != "${MACHINE_ARCH}" ]; then
+                    grep -w "$line" $HIDDEN_ROOTFS_DIR/etc/dnf/vars/arch > /dev/null
+                    if [ $? -ne 0 ]; then
+                        echo -n "$line:" >> $HIDDEN_ROOTFS_DIR/etc/dnf/vars/arch
+                        echo -n " $line" >> $HIDDEN_ROOTFS_DIR/etc/rpmrc
+                    fi
+                fi
+            fi
+            continue
+        fi
+    done
+    cd - >/dev/null
+}
+
+config_dnf () {
+    #necessary dnf config
+    if [ ! -d $HIDDEN_ROOTFS_DIR/etc/dnf ]; then
+        mkdir -p $HIDDEN_ROOTFS_DIR/etc/dnf
+        touch $HIDDEN_ROOTFS_DIR/etc/dnf/dnf-host.conf
+    fi
+    
+    #clean the original content in dnf.conf file
+    #Add config_path in dnf.conf file
+
+cat > $HIDDEN_ROOTFS_DIR/etc/dnf/dnf-host.conf <<EOF
+[main]
+spdx_repodir=$DEFINE_SPDX_REPO_DIR
+spdx_download=$DEFINE_SPDX_DESTINATION_DIR
+srpm_repodir=$DEFINE_SRPM_REPO_DIR
+srpm_download=$DEFINE_SRPM_DESTINATION_DIR
+rpm_repodir=$DEFINE_RPM_REPO_DIR
+rpm_download=$DEFINE_RPM_DESTINATION_DIR
+
+installroot=$HIDDEN_ROOTFS_DIR
+logdir=$WORKDIR
+releasever=None
+EOF
+    
+    #Config local repo for cross environment
+    mkdir -p $HIDDEN_ROOTFS_DIR/etc/yum.repos.d
+
+cat > $HIDDEN_ROOTFS_DIR/etc/yum.repos.d/oe.repo  <<EOF
+[base]
+name=oe_repo
+baseurl=file://$DEFINE_REPO_DIR
+enabled=1
+gpgcheck=0 
+EOF
+
+    if [ ! -d $HIDDEN_ROOTFS_DIR/etc/dnf/vars ]; then
+        mkdir -p $HIDDEN_ROOTFS_DIR/etc/dnf/vars
+        echo -n "${MACHINE_ARCH}:${ARCH}:" >> $HIDDEN_ROOTFS_DIR/etc/dnf/vars/arch
+    fi
+
+    #necessary rpm config
+    if [ ! -d $HIDDEN_ROOTFS_DIR/etc/rpm ] || [ ! -f $HIDDEN_ROOTFS_DIR/etc/rpm/platform ]; then
+        mkdir -p $HIDDEN_ROOTFS_DIR/etc/rpm
+        echo "${MACHINE_ARCH}-pc-linux" > $HIDDEN_ROOTFS_DIR/etc/rpm/platform
+    fi
+
+    if [ ! -f $HIDDEN_ROOTFS_DIR/etc/rpmrc ]; then
+        echo -n "arch_compat: ${MACHINE_ARCH}: all any noarch ${ARCH} ${MACHINE_ARCH}" > $HIDDEN_ROOTFS_DIR/etc/rpmrc
+    fi
+
+    echo "Scanning repo ..."
+    travFolder $DEFINE_REPO_DIR
+    sed -i "s/:$/\n/g" $HIDDEN_ROOTFS_DIR/etc/dnf/vars/arch
+    sed -i "s/:$//g" $HIDDEN_ROOTFS_DIR/etc/rpmrc
+}
+
 dnf-init() {
     if [ -f .env-dnf ];then
         rm .env-dnf
@@ -153,7 +290,11 @@ dnf-init() {
         DEFINE_REPO_DIR=${DEFINE_REPO_DIR#*//}
     fi
 
-    environment-dnf.sh $HIDDEN_ROOTFS_DIR $DEFINE_REPO_DIR $DEFINE_SPDX_REPO_DIR $DEFINE_SPDX_DESTINATION_DIR $DEFINE_SRPM_REPO_DIR $DEFINE_SRPM_DESTINATION_DIR $DEFINE_RPM_REPO_DIR $DEFINE_RPM_DESTINATION_DIR $DEFINE_ROOTFS_DIR
+    #Start from here
+    export_env
+    check_para
+    create_repo
+    config_dnf
 }
 
 dnf-show() {
